server:
  port: 8080
  application-name: goods-doc-lang
  servlet:
    context-path: /goods

logging:
  level:
    com.hq.goods.lang.utils: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doclang?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


deepseek:
  api:
    url: https://api.deepseek.com
    key: xxx

hq:
  lang:
    ai:
      proxy: false
      aihubmixUrl: https://api.inferera.com
      aihubmixKey: xxx
      deepseekKey: xxx

mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml

swagger:
  enable: true
